import{afterEach,beforeEach,describe,expect,it}from"vitest";import{buildApp}from"../src/app.js";import{Store}from"../src/store.js";let app:any,store:Store;const origin="http://127.0.0.1:4173";beforeEach(async()=>{store=new Store();app=await buildApp({store,config:{NODE_ENV:"test",FRONTEND_ORIGIN:origin,SESSION_SECRET:"12345678901234567890123456789012",IDENTITY_MODE:"mock"}})});afterEach(()=>app.close());
async function login(userId="personal-user-a"){const r=await app.inject({method:"POST",url:"/api/v1/auth/mock-login",payload:{userId}}),cookie=r.cookies[0].name+"="+r.cookies[0].value;return{cookie,csrf:r.json().csrfToken}}
const write=(auth:any,method:string,url:string,payload?:unknown)=>app.inject({method,url,payload,headers:{cookie:auth.cookie,origin,"x-csrf-token":auth.csrf}});
describe("sicheres API-Fundament",()=>{
it("liefert Health und Readiness ohne Secrets",async()=>{expect((await app.inject({url:"/api/v1/health"})).json()).toEqual({status:"ok"});expect(JSON.stringify((await app.inject({url:"/api/v1/readiness"})).json())).not.toContain("secret")});
it("erzeugt und rotiert serverseitige Sitzungen",async()=>{const a=await login(),b=await login();expect(a.cookie).not.toBe(b.cookie);expect(store.sessions.size).toBe(1)});
it("trennt Nutzerlisten vollständig",async()=>{const a=await login("personal-user-a"),b=await login("personal-user-b");const ar=(await app.inject({url:"/api/v1/classes",headers:{cookie:a.cookie}})).json(),br=(await app.inject({url:"/api/v1/classes",headers:{cookie:b.cookie}})).json();expect(ar.items.map((x:any)=>x.title)).toEqual(["Klasse 2a"]);expect(br.items.map((x:any)=>x.title)).toEqual(["Klasse 3a"])});
it("blockiert IDOR lesen, ändern und archivieren zurückhaltend",async()=>{const a=await login("personal-user-a");expect((await app.inject({url:"/api/v1/materials/material-b",headers:{cookie:a.cookie}})).statusCode).toBe(404);expect((await write(a,"PATCH","/api/v1/resources/material-b",{title:"Fremd",version:1})).statusCode).toBe(404);expect((await write(a,"DELETE","/api/v1/resources/material-b")).statusCode).toBe(404);expect(store.resources.get("material-b")?.title).toBe("Material B")});
it("ignoriert manipulierte Workspace-ID und blockiert fremde Verknüpfung",async()=>{const a=await login();const r=await write(a,"POST","/api/v1/resources",{kind:"material",title:"Eigen",workspaceId:"workspace-b",parentId:"lesson-b"});expect(r.statusCode).toBe(404);expect([...store.resources.values()].filter(x=>x.title==="Eigen")).toHaveLength(0)});
it("erzwingt Origin und CSRF",async()=>{const a=await login();expect((await app.inject({method:"POST",url:"/api/v1/resources",payload:{kind:"class",title:"X"},headers:{cookie:a.cookie,origin:"https://evil.invalid","x-csrf-token":a.csrf}})).json().error.code).toBe("ORIGIN_DENIED");expect((await app.inject({method:"POST",url:"/api/v1/resources",payload:{kind:"class",title:"X"},headers:{cookie:a.cookie,origin}})).json().error.code).toBe("CSRF_INVALID")});
it("archiviert weich und erkennt Versionskonflikte",async()=>{const a=await login();expect((await write(a,"PATCH","/api/v1/resources/lesson-a",{title:"Neu",version:99})).statusCode).toBe(409);expect((await write(a,"DELETE","/api/v1/resources/lesson-a")).statusCode).toBe(200);expect(store.resources.get("lesson-a")?.archivedAt).toBeTruthy()});
it("führt Vorschau schreibfrei und Import idempotent aus",async()=>{const a=await login(),payload={objects:[{localId:"c1",kind:"class",title:"Klasse 4a"},{localId:"t1",kind:"topic",title:"Wasser",parentLocalId:"c1"}]};const before=store.resources.size,p=await write(a,"POST","/api/v1/import/local-preview",payload);expect(store.resources.size).toBe(before);const j=p.json(),c=await write(a,"POST","/api/v1/import/local-commit",{previewId:j.id,hash:j.hash});expect(c.json().imported).toBe(2);expect((await write(a,"POST","/api/v1/import/local-commit",{previewId:j.id,hash:j.hash})).json().error.code).toBe("IMPORT_ALREADY_APPLIED")});
it("importiert ausschließlich in eigenen Workspace",async()=>{const a=await login(),p=(await write(a,"POST","/api/v1/import/local-preview",{objects:[{localId:"x",kind:"class",title:"Nur A"}]})).json();await write(a,"POST","/api/v1/import/local-commit",{previewId:p.id,hash:p.hash});expect([...store.resources.values()].find(x=>x.title==="Nur A")?.workspaceId).toBe("workspace-a")});
it("Buddy lädt Kontext serverseitig und mutiert nicht",async()=>{const a=await login(),before={...store.resources.get("lesson-a")};const r=await write(a,"POST","/api/v1/buddy/requests",{targetType:"lesson",targetId:"lesson-a",capabilityKey:"shorten_lesson",context:{title:"Manipuliert"}});expect(r.statusCode).toBe(200);expect(r.json().summary).toContain("Stunde A");expect(store.resources.get("lesson-a")).toEqual(before)});
it("Buddy blockiert fremde Ziele und Budget",async()=>{const a=await login();expect((await write(a,"POST","/api/v1/buddy/requests",{targetType:"lesson",targetId:"lesson-b",capabilityKey:"shorten_lesson"})).statusCode).toBe(404);store.buddyUsage.set("workspace-a",50);expect((await write(a,"POST","/api/v1/buddy/requests",{targetType:"lesson",targetId:"lesson-a",capabilityKey:"shorten_lesson"})).json().error.code).toBe("BUDDY_BUDGET_EXCEEDED")});
it("Logout A beeinflusst B nicht",async()=>{const a=await login("personal-user-a"),b=await login("personal-user-b");await write(a,"POST","/api/v1/auth/logout");expect((await app.inject({url:"/api/v1/session",headers:{cookie:a.cookie}})).statusCode).toBe(401);expect((await app.inject({url:"/api/v1/session",headers:{cookie:b.cookie}})).statusCode).toBe(200)});
});
