// @vitest-environment jsdom
import{beforeEach,describe,expect,it}from"vitest";import{render,screen}from"@testing-library/react";import userEvent from"@testing-library/user-event";import{MemoryRouter}from"react-router-dom";import{AppRoutes}from"../../app/router";import{domainDb}from"../../domain";beforeEach(async()=>{await domainDb.delete();await domainDb.open()});const at=(p:string)=>render(<MemoryRouter initialEntries={[p]}><AppRoutes/></MemoryRouter>);
describe("Stundenoberflächen",()=>{
it("zeigt ausgearbeitete und offene Gliederungspunkte",async()=>{at("/reihen/implementation-nomen");expect(await screen.findByRole("heading",{name:"Unterrichtsstunden"})).toBeInTheDocument();expect(screen.getAllByText("Noch nicht ausgearbeitet").length).toBeGreaterThan(0)});
it("öffnet den echten Stundenarbeitsplatz mit Kontext",async()=>{at("/stunden/lesson-nomen-1");expect(await screen.findByRole("heading",{name:"Nomen kennenlernen",level:1})).toBeInTheDocument();expect(screen.getByText("Klasse 2a · Nomen entdecken · Stunde 1")).toBeInTheDocument()});
it("zeigt die Zeitabweichung ruhig",async()=>{at("/stunden/lesson-nomen-1");expect(await screen.findByText("Die Phasen ergeben 50 Minuten, geplant sind 45 Minuten.")).toBeInTheDocument()});
it("wechselt kompakt und ausführlich ohne anderes Modell",async()=>{const u=userEvent.setup();at("/stunden/lesson-nomen-1?mode=compact");expect(await screen.findByLabelText("Lernziel")).toBeInTheDocument();await u.click(screen.getByLabelText("Ausführlich"));expect(await screen.findByText("Lernvoraussetzungen")).toBeInTheDocument()});
it("öffnet Phasendialog und Statusdialog",async()=>{const u=userEvent.setup();at("/stunden/lesson-nomen-1");await screen.findByRole("heading",{name:"Nomen kennenlernen",level:1});await u.click(screen.getByRole("button",{name:"Phase ergänzen"}));expect(screen.getByRole("dialog",{name:"Unterrichtsphase ergänzen"})).toBeInTheDocument()});
it("sortiert Phasen per Tastatur",async()=>{const u=userEvent.setup();at("/stunden/lesson-nomen-1");const b=await screen.findByRole("button",{name:"Nomen und Artikel ordnen nach oben"});b.focus();await u.keyboard("{Enter}");expect(b).toHaveFocus()});
it("öffnet Reflexion",async()=>{const u=userEvent.setup();at("/stunden/lesson-nomen-1");await screen.findByRole("heading",{name:"Nomen kennenlernen",level:1});await u.click(screen.getByRole("button",{name:"Kurz reflektieren"}));expect(screen.getByRole("dialog",{name:"Stunde kurz reflektieren"})).toBeInTheDocument()});
it("zeigt ungültige Route ruhig",async()=>{at("/stunden/unbekannt");expect(await screen.findByRole("heading",{name:"Unterrichtsstunde nicht gefunden"})).toBeInTheDocument()});
});
