import { domainDb } from "../domain/database";
import { sha256 } from "./checksum";
import { BackupError } from "./contracts";

type ExchangePackage = { format:"lehrerkompass-series"|"lehrerkompass-material";formatVersion:1;exportedAt:string;privacy:{excluded:string[]};data:Record<string,unknown[]>;checksum:string };
const clean = (row:unknown) => { if(!row||typeof row!=="object") return row; const blocked=new Set(["reflection","privateNotes","classLabel","calendarEventId","buddyHistory","oneDrivePath","filePath"]); return Object.fromEntries(Object.entries(row as Record<string,unknown>).filter(([key])=>!blocked.has(key))); };
async function pack(format:ExchangePackage["format"],data:Record<string,unknown[]>):Promise<ExchangePackage>{const base={format,formatVersion:1 as const,exportedAt:new Date().toISOString(),privacy:{excluded:["Klassenbezeichnung","Reflexionen","private Notizen","Kalenderdaten","Buddy-Verlauf","externe Dateipfade"]},data};return{...base,checksum:await sha256(base)}}
export async function exportSeries(templateId:string,includeLessons=false,includeMaterials=false){const template=await domainDb.seriesTemplates.get(templateId);if(!template)throw new BackupError("BACKUP_FILE_INVALID","Die Reihe wurde nicht gefunden.");const implementations=await domainDb.seriesImplementations.where("templateId").equals(templateId).toArray();const implementationIds=implementations.map(v=>v.id);const data:Record<string,unknown[]>={seriesTemplates:[clean(template)],seriesImplementations:implementations.map(clean),seriesPlannings:(await domainDb.seriesPlannings.where("implementationId").anyOf(implementationIds).toArray()).map(clean),seriesSequenceItems:(await domainDb.seriesSequenceItems.where("implementationId").anyOf(implementationIds).toArray()).map(clean)};if(includeLessons)data.lessons=(await domainDb.lessons.where("implementationId").anyOf(implementationIds).toArray()).map(clean);if(includeMaterials)data.materials=(await domainDb.materials.toArray()).filter(v=>implementationIds.includes(v.lessonId??"")).map(clean);return pack("lehrerkompass-series",data)}
export async function exportMaterial(materialId:string){const material=await domainDb.materials.get(materialId);if(!material)throw new BackupError("BACKUP_FILE_INVALID","Das Material wurde nicht gefunden.");const documents=await domainDb.materialDocuments.where("materialId").equals(materialId).toArray();const pages=await domainDb.materialPages.where("documentId").anyOf(documents.map(v=>v.id)).toArray();const blocks=await domainDb.materialBlocks.where("pageId").anyOf(pages.map(v=>v.id)).toArray();return pack("lehrerkompass-material",{materials:[clean(material)],materialDocuments:documents.map(clean),materialPages:pages.map(clean),materialBlocks:blocks.map(clean),materialSolutions:(await domainDb.materialSolutions.where("taskBlockId").anyOf(blocks.map(v=>v.id)).toArray()).map(clean)})}
export async function parseExchange(text:string){let raw:unknown;try{raw=JSON.parse(text)}catch{throw new BackupError("BACKUP_FILE_INVALID","Die Austauschdatei ist beschädigt.")}if(!raw||typeof raw!=="object"||!("checksum" in raw)||!("format" in raw))throw new BackupError("BACKUP_FILE_INVALID","Unbekanntes Austauschformat.");const {checksum,...base}=raw as ExchangePackage;if(await sha256(base)!==checksum)throw new BackupError("BACKUP_CHECKSUM_INVALID","Die Austauschdatei ist beschädigt.");if(JSON.stringify(base).match(/<script|javascript:|onedrivePath|filePath/i))throw new BackupError("BACKUP_FILE_INVALID","Ausführbare Inhalte oder fremde Dateipfade sind nicht zulässig.");return raw as ExchangePackage}
export function remapExchangeIds(pkg:ExchangePackage){const map=new Map<string,string>();const data=Object.fromEntries(Object.entries(pkg.data).map(([name,rows])=>[name,rows.map(row=>{const source=row as Record<string,unknown>;const old=String(source.id??crypto.randomUUID());if(!map.has(old))map.set(old,crypto.randomUUID());const next=Object.fromEntries(Object.entries(source).map(([key,value])=>[key,key==="id"?map.get(old):typeof value==="string"&&map.has(value)?map.get(value):value]));return next;})]));return{...pkg,data};}
