import "fake-indexeddb/auto";
import Dexie from "dexie";
import {afterEach,beforeEach,describe,expect,it} from "vitest";
import {CalendarService,DomainDatabase,DomainService,LessonService,SeriesService,CALENDAR_SEED,LESSON_SEED,SERIES_SEED} from "..";

let db:DomainDatabase,service:CalendarService;
beforeEach(async()=>{db=new DomainDatabase(`calendar-${crypto.randomUUID()}`);await new DomainService(db).ready();await new SeriesService(db).ready();await new LessonService(db).ready();service=new CalendarService(db);await service.ready()});
afterEach(()=>db.delete());
const fails=(p:Promise<unknown>,code:string)=>expect(p).rejects.toMatchObject({code});
describe("Kalender-Domain",()=>{
  it("hält Unterrichtsstunde und Termin getrennt",async()=>{const lesson=await db.lessons.get(LESSON_SEED.lesson),event=await db.calendarEvents.get(CALENDAR_SEED.event);expect(lesson).not.toHaveProperty("date");expect(event).toMatchObject({lessonId:LESSON_SEED.lesson,date:CALENDAR_SEED.date})});
  it("verhindert überlappende Unterrichtsblöcke",()=>fails(service.createPeriod({label:"Kollision",startsAt:"08:30",endsAt:"09:00"}),"CALENDAR_PERIOD_OVERLAP"));
  it("verhindert doppelte Wochenbelegung",()=>fails(service.createSlot({schoolYearId:"year-2026",weekday:1,periodId:"period-1",classId:"class-2a",subjectId:"subject-deutsch"}),"CALENDAR_SLOT_CONFLICT"));
  it("erlaubt Termin ohne Stunde",async()=>expect(await service.createEvent({schoolYearId:"year-2026",date:"2026-08-27",periodId:"period-4",title:"Schwimmen",eventType:"school_event"})).toEqual(expect.any(String)));
  it("verhindert mehrere aktive Termine derselben Stunde",()=>fails(service.createEvent({schoolYearId:"year-2026",date:"2026-08-25",periodId:"period-2",classId:"class-2a",subjectId:"subject-deutsch",lessonId:LESSON_SEED.lesson,title:"Doppelt",eventType:"lesson"}),"CALENDAR_LESSON_ALREADY_SCHEDULED"));
  it("prüft Datum gegen Schuljahr",()=>fails(service.createEvent({schoolYearId:"year-2026",date:"2028-01-01",periodId:"period-2",title:"Außerhalb",eventType:"organization"}),"CALENDAR_DATE_OUTSIDE_YEAR"));
  it("verschiebt transaktional und erhält Planung",async()=>{const before=await db.lessonPlannings.get(LESSON_SEED.planning),newId=await service.moveEvent(CALENDAR_SEED.event,{date:"2026-08-25",periodId:"period-3"});expect(await db.calendarEvents.get(CALENDAR_SEED.event)).toMatchObject({status:"moved"});expect(await db.calendarEvents.get(newId)).toMatchObject({movedFromEventId:CALENDAR_SEED.event,date:"2026-08-25"});expect(await db.lessonPlannings.get(LESSON_SEED.planning)).toEqual(before)});
  it("rollt fehlgeschlagene Verschiebung zurück",async()=>{await fails(service.moveEvent(CALENDAR_SEED.event,{date:"2026-08-26",periodId:"period-3"}),"CALENDAR_EVENT_CONFLICT");expect(await db.calendarEvents.get(CALENDAR_SEED.event)).toMatchObject({status:"planned",date:CALENDAR_SEED.date})});
  it("Ausfall löscht die Stunde nicht",async()=>{await service.changeStatus(CALENDAR_SEED.event,"cancelled");expect(await db.calendarEvents.get(CALENDAR_SEED.event)).toMatchObject({status:"cancelled"});expect(await db.lessons.get(LESSON_SEED.lesson)).toBeTruthy()});
  it("markiert optional auch eine einsatzbereite Stunde durchgeführt",async()=>{await db.lessons.update(LESSON_SEED.lesson,{status:"ready"});await service.changeStatus(CALENDAR_SEED.event,"completed",true);expect(await db.lessons.get(LESSON_SEED.lesson)).toMatchObject({status:"completed"})});
  it("verhindert ungültige Statusübergänge",async()=>{await service.changeStatus(CALENDAR_SEED.event,"completed");await fails(service.changeStatus(CALENDAR_SEED.event,"cancelled"),"CALENDAR_INVALID_STATUS_TRANSITION")});
  it("Tagesübersicht übernimmt vorhandene freigegebene Planung",async()=>{await db.lessonPlannings.update(LESSON_SEED.planning,{lessonGoal:"Nomen erkennen",materialNeeds:"Wortkarten",preparation:"Karten auslegen",notes:"Privat"});const row=(await service.dayOverview(CALENDAR_SEED.date))[0]!;expect(row).toMatchObject({lessonGoal:"Nomen erkennen",materialNeeds:"Wortkarten"});expect(row).not.toHaveProperty("notes")});
  it("Vertretungsübersicht schließt Terminnotizen aus",async()=>{await db.calendarEvents.update(CALENDAR_SEED.event,{notes:"Interne Beobachtung"});const row=(await service.dayOverview(CALENDAR_SEED.date,true))[0]!;expect(row.organizational).toBeUndefined();expect(JSON.stringify(row)).not.toContain("Interne Beobachtung")});
  it("findet nur Stunden ohne aktiven Termin",async()=>{const free=await new LessonService(db).create({implementationId:SERIES_SEED.implementation,title:"Ungeplant",duration:45});expect((await service.unscheduledLessons()).map(v=>v.id)).toContain(free);expect((await service.unscheduledLessons()).map(v=>v.id)).not.toContain(LESSON_SEED.lesson)});
});

const v1={schoolYears:"id,isActive,archivedAt",classes:"id,schoolYearId,isActive,archivedAt",subjects:"id,key,sortOrder",classSubjects:"id,classId,subjectId,[classId+subjectId],sortOrder",topics:"id,classId,subjectId,[classId+subjectId],status,sortOrder",meta:"id"};
const v2={...v1,seriesTemplates:"id,topicId,status,[topicId+title]",seriesImplementations:"id,templateId,classId,schoolYearId,status",seriesPlannings:"id,implementationId",seriesSequenceItems:"id,implementationId,[implementationId+position]",seriesWorkbenchRefs:"id,implementationId,isActive"};
const v3={...v2,lessons:"id,implementationId,sequenceItemId,[implementationId+position],status,archivedAt",lessonPlannings:"id,lessonId",lessonPhases:"id,lessonId,[lessonId+position]",lessonReflections:"id,lessonId",lessonWorkbenchRefs:"id,lessonId,isActive"};
it("migriert v3 über v4 bis v7 und erhält Unterrichtsstunden",async()=>{const n=`calendar-v3-${crypto.randomUUID()}`,old=new Dexie(n);old.version(3).stores(v3);await old.open();await old.table("lessons").add({id:"kept-lesson",implementationId:"i",position:0,title:"Bleibt",plannedDurationMinutes:45,status:"draft",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"});old.close();const next=new DomainDatabase(n);await next.open();expect(await next.lessons.get("kept-lesson")).toBeTruthy();expect(next.verno).toBe(7);await next.delete()});
it("migriert vollständig v1 bis v7",async()=>{const n=`calendar-v1-${crypto.randomUUID()}`,old=new Dexie(n);old.version(1).stores(v1);await old.open();await old.table("topics").add({id:"kept-topic",classId:"c",subjectId:"s",title:"Bleibt",sortOrder:0,status:"active",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"});old.close();const next=new DomainDatabase(n);await next.open();expect(await next.topics.get("kept-topic")).toBeTruthy();expect(next.verno).toBe(7);await next.delete()});
