import"fake-indexeddb/auto";import Dexie from"dexie";import{afterEach,beforeEach,describe,expect,it}from"vitest";import{DomainDatabase,DomainService,SeriesService,SEED_IDS,SERIES_SEED}from"..";
let db:DomainDatabase,series:SeriesService;beforeEach(async()=>{db=new DomainDatabase(`series-${crypto.randomUUID()}`);await new DomainService(db).ready();series=new SeriesService(db);await series.ready()});afterEach(()=>db.delete());const fails=(p:Promise<unknown>,code:string)=>expect(p).rejects.toMatchObject({code});
describe("Unterrichtsreihen",()=>{
it("ordnet die Stammreihe einem Thema zu",async()=>expect(await db.seriesTemplates.get(SERIES_SEED.template)).toMatchObject({topicId:SEED_IDS.topicNouns}));
it("trennt Durchführung von Stammreihe und Klasse",async()=>expect(await db.seriesImplementations.get(SERIES_SEED.implementation)).toMatchObject({templateId:SERIES_SEED.template,classId:SEED_IDS.class2a}));
it("verhindert doppelte Titel im Thema",()=>fails(series.createSeries({topicId:SEED_IDS.topicNouns,classId:SEED_IDS.class2a,title:" nomen   entdecken "}),"SERIES_TEMPLATE_DUPLICATE_TITLE"));
it("erlaubt mehrere Durchführungen einer Stammreihe",async()=>{const id=await series.createSeries({topicId:SEED_IDS.topicNouns,classId:SEED_IDS.class2a,title:"",useTemplateId:SERIES_SEED.template});expect(await db.seriesImplementations.get(id)).toBeTruthy()});
it("prüft Klasse und Thema",()=>fails(series.createSeries({topicId:SEED_IDS.topicNouns,classId:SEED_IDS.class3a,title:"Andere"}),"SERIES_CLASS_TOPIC_MISMATCH"));
it("erlaubt den linearen Statuspfad",async()=>{await series.updateStatus(SERIES_SEED.implementation,"ready");await series.updateStatus(SERIES_SEED.implementation,"in_progress");await series.updateStatus(SERIES_SEED.implementation,"completed");expect(await db.seriesImplementations.get(SERIES_SEED.implementation)).toMatchObject({status:"completed"})});
it("verhindert ungültige Statussprünge",()=>fails(series.updateStatus(SERIES_SEED.implementation,"completed"),"SERIES_INVALID_STATUS_TRANSITION"));
it("archiviert ohne Planung zu löschen und kann wiederherstellen",async()=>{await series.archive(SERIES_SEED.implementation);expect(await db.seriesPlannings.get(SERIES_SEED.planning)).toBeTruthy();await series.restore(SERIES_SEED.implementation);expect(await db.seriesImplementations.get(SERIES_SEED.implementation)).toMatchObject({status:"planning"})});
it("speichert unvollständige Grundplanung",async()=>{await series.savePlanning(SERIES_SEED.implementation,{foundations:"Arbeitsplan"});expect(await db.seriesPlannings.get(SERIES_SEED.planning)).toMatchObject({foundations:"Arbeitsplan",learningPrerequisites:""})});
it("sortiert die Stundenfolge persistent",async()=>{const before=await db.seriesSequenceItems.where("implementationId").equals(SERIES_SEED.implementation).sortBy("position");await series.reorderSequence(SERIES_SEED.implementation,before[1]!.id,-1);const after=await db.seriesSequenceItems.where("implementationId").equals(SERIES_SEED.implementation).sortBy("position");expect(after[0]!.id).toBe(before[1]!.id)});
it("nimmt nur den Verweis von der Werkbank",async()=>{await series.toggleWorkbench(SERIES_SEED.implementation,false);expect(await db.seriesImplementations.get(SERIES_SEED.implementation)).toBeTruthy();expect(await db.seriesWorkbenchRefs.get("series-ref-nomen")).toMatchObject({isActive:false})});
it("rollt transaktionale Anlage bei Fehler zurück",async()=>{const before=await db.seriesTemplates.count();await fails(series.createSeries({topicId:"missing",classId:SEED_IDS.class2a,title:"Fehler"}),"SERIES_CLASS_TOPIC_MISMATCH");expect(await db.seriesTemplates.count()).toBe(before)});
});
it("migriert v1 auf das aktuelle Schema und erhält Paket-04-Daten",async()=>{const name=`migration-${crypto.randomUUID()}`,legacy=new Dexie(name);legacy.version(1).stores({schoolYears:"id,isActive,archivedAt",classes:"id,schoolYearId,isActive,archivedAt",subjects:"id,key,sortOrder",classSubjects:"id,classId,subjectId,[classId+subjectId],sortOrder",topics:"id,classId,subjectId,[classId+subjectId],status,sortOrder",meta:"id"});await legacy.open();await legacy.table("topics").add({id:"kept-topic",classId:"c",subjectId:"s",title:"Bleibt",sortOrder:0,status:"active",createdAt:"2026-07-15T00:00:00.000Z",updatedAt:"2026-07-15T00:00:00.000Z"});legacy.close();const migrated=new DomainDatabase(name);await migrated.open();expect(await migrated.topics.get("kept-topic")).toMatchObject({title:"Bleibt"});expect(migrated.verno).toBe(7);await migrated.delete()});
