// @vitest-environment jsdom
import{beforeEach,describe,expect,it}from"vitest";import{render,screen,waitFor}from"@testing-library/react";import userEvent from"@testing-library/user-event";import{MemoryRouter}from"react-router-dom";import{AppRoutes}from"../../app/router";import{domainDb}from"../../domain";
beforeEach(async()=>{await domainDb.delete();await domainDb.open()});const at=(path:string)=>render(<MemoryRouter initialEntries={[path]}><AppRoutes/></MemoryRouter>);
describe("Reihenoberflächen",()=>{
it("zeigt Stammreihe und Durchführung im Thema",async()=>{at("/klassen/class-2a/faecher/subject-deutsch/themen/topic-nomen");expect(await screen.findByRole("heading",{name:"Nomen",level:1})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Aktuell für diese Klasse"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Wiederverwendbare Reihen"})).toBeInTheDocument()});
it("öffnet den Reihendialog",async()=>{const u=userEvent.setup();at("/klassen/class-2a/faecher/subject-deutsch/themen/topic-nomen");await screen.findByRole("heading",{name:"Nomen",level:1});await u.click(screen.getByRole("button",{name:"Unterrichtsreihe anlegen"}));expect(screen.getByRole("dialog",{name:"Unterrichtsreihe anlegen"})).toBeInTheDocument()});
it("zeigt den korrekten Dashboardkontext",async()=>{at("/reihen/implementation-nomen");expect(await screen.findByRole("heading",{name:"Nomen entdecken",level:1})).toBeInTheDocument();expect(screen.getByText("Klasse 2a · Deutsch · Nomen · 2026/27")).toBeInTheDocument()});
it("ändert einen erlaubten Status",async()=>{const u=userEvent.setup();at("/reihen/implementation-nomen");await screen.findByRole("heading",{name:"Nomen entdecken",level:1});await u.click(screen.getByRole("button",{name:"Status ändern"}));expect(screen.getByRole("dialog",{name:"Status ändern"})).toBeInTheDocument();await u.click(screen.getByRole("button",{name:"Status übernehmen"}));await waitFor(()=>expect(screen.getByText("Einsatzbereit")).toBeInTheDocument())});
it("bearbeitet Grundplanung lokal",async()=>{const u=userEvent.setup();at("/reihen/implementation-nomen");const field=await screen.findByLabelText("Grundlagen und Quellen");await u.type(field,"Arbeitsplan");await u.tab();await waitFor(()=>expect(field).toHaveValue("Arbeitsplan"))});
it("sortiert die Stundenfolge per Tastatur",async()=>{const u=userEvent.setup();at("/reihen/implementation-nomen");const b=await screen.findByRole("button",{name:"Artikel zuordnen nach oben"});b.focus();await u.keyboard("{Enter}");expect(b).toHaveFocus()});
it("zeigt ungültige Durchführung ruhig",async()=>{at("/reihen/missing");expect(await screen.findByRole("heading",{name:"Durchführung nicht gefunden"})).toBeInTheDocument()});
it("verwendet Dialog statt nativen Prompt und zeigt Klassenstufenhinweis",async()=>{const u=userEvent.setup();at("/klassen/class-2a");await screen.findByRole("heading",{name:"Klasse 2a"});await u.click(screen.getByRole("button",{name:"Klasse bearbeiten"}));expect(screen.getByText("Die Klassenstufe beeinflusst spätere fachliche Zuordnungen und Vorschläge. Bestehende Inhalte bleiben gespeichert.")).toBeInTheDocument()});
});
