// @vitest-environment jsdom
import "fake-indexeddb/auto";import{beforeEach,describe,expect,it}from"vitest";import{render,screen,waitFor}from"@testing-library/react";import userEvent from"@testing-library/user-event";import{MemoryRouter}from"react-router-dom";import{AppRoutes}from"../../../app/router";import{domainDb}from"../../../domain";
beforeEach(async()=>{await domainDb.delete();await domainDb.open()});const renderAt=(path:string)=>render(<MemoryRouter initialEntries={[path]}><AppRoutes/></MemoryRouter>);
describe("Klassenarbeitsplatz",()=>{
it("zeigt aktive Klassen und Schuljahr",async()=>{renderAt("/klassen");expect(await screen.findByRole("heading",{name:"Klassen"})).toBeInTheDocument();expect(await screen.findByText("Aktives Schuljahr: 2026/27")).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Klasse 2a"})).toBeInTheDocument()});
it("öffnet den Dialog und validiert Pflichtfelder",async()=>{const u=userEvent.setup();renderAt("/klassen");await screen.findByRole("heading",{name:"Klassen"});await u.click(screen.getByRole("button",{name:"Klasse anlegen"}));expect(screen.getByRole("dialog")).toBeInTheDocument();expect(screen.getByLabelText("Klassenbezeichnung")).toBeRequired()});
it("öffnet eine Klassendetailroute",async()=>{renderAt("/klassen/class-2a");expect(await screen.findByRole("heading",{name:"Klasse 2a"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Deutsch"})).toBeInTheDocument()});
it("zeigt Themen in der Fachroute",async()=>{renderAt("/klassen/class-2a/faecher/subject-deutsch");expect(await screen.findByRole("heading",{name:"Deutsch",level:1})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Nomen"})).toBeInTheDocument()});
it("deaktiviert ein Fach und bewahrt dessen Themen",async()=>{const u=userEvent.setup();renderAt("/klassen/class-2a");await screen.findByRole("heading",{name:"Klasse 2a"});await u.click(screen.getByRole("button",{name:"Fächer verwalten"}));await u.click(screen.getByLabelText("Deutsch"));await waitFor(()=>expect(screen.queryByRole("heading",{name:"Deutsch"})).not.toBeInTheDocument());expect(await domainDb.topics.get("topic-nomen")).toBeTruthy()});
it("zeigt ungültige Klassen ruhig",async()=>{renderAt("/klassen/unbekannt");expect(await screen.findByRole("heading",{name:"Klasse nicht gefunden"})).toBeInTheDocument()});
it("erreicht Sortieraktionen per Tastatur",async()=>{const u=userEvent.setup();renderAt("/klassen/class-2a/faecher/subject-deutsch");const button=await screen.findByRole("button",{name:"Lesen und Textverständnis nach oben"});button.focus();await u.keyboard("{Enter}");expect(button).toHaveFocus()});
it("zeigt die Schuljahresverwaltung",async()=>{renderAt("/klassen/schuljahre");expect(await screen.findByRole("heading",{name:"Schuljahre verwalten"})).toBeInTheDocument();expect(screen.getByText("2026/27")).toBeInTheDocument()});
});
