import{z}from"zod";import{isoTime}from"./model";
export const LESSON_STATUSES=["draft","planning","ready","completed","cancelled","needs_revision"]as const;export const PHASE_TYPES=["arrival","diagnosis","introduction","activation","development","practice","consolidation","transfer","reflection","organization","other"]as const;export type LessonStatus=(typeof LESSON_STATUSES)[number];
export type PhaseType=(typeof PHASE_TYPES)[number];
export const lessonSchema=z.object({id:z.string(),implementationId:z.string(),sequenceItemId:z.string().optional(),position:z.number().int().nonnegative(),title:z.string().min(1),shortDescription:z.string().optional(),plannedDurationMinutes:z.number().int().positive(),status:z.enum(LESSON_STATUSES),createdAt:isoTime,updatedAt:isoTime,completedAt:isoTime.optional(),archivedAt:isoTime.optional()});
export const lessonPlanningSchema=z.object({id:z.string(),lessonId:z.string(),seriesContext:z.string().optional(),learningPrerequisites:z.string(),lessonGoal:z.string(),successCriteria:z.string().optional(),vocabulary:z.string().optional(),differentiation:z.string(),materialNeeds:z.string(),preparation:z.string(),homework:z.string().optional(),notes:z.string().optional(),createdAt:isoTime,updatedAt:isoTime});
export const lessonPhaseSchema=z.object({id:z.string(),lessonId:z.string(),position:z.number().int().nonnegative(),phaseType:z.enum(PHASE_TYPES),title:z.string().min(1),durationMinutes:z.number().int().positive(),teacherAction:z.string().optional(),studentAction:z.string().optional(),method:z.string().optional(),socialForm:z.string().optional(),mediaAndMaterial:z.string().optional(),differentiationNote:z.string().optional(),optional:z.boolean(),createdAt:isoTime,updatedAt:isoTime});
export const lessonReflectionSchema=z.object({id:z.string(),lessonId:z.string(),actualDurationMinutes:z.number().int().positive().optional(),workedWell:z.string().optional(),challenges:z.string().optional(),nextTimeChange:z.string().optional(),groupObservation:z.string().optional(),followUp:z.string().optional(),createdAt:isoTime,updatedAt:isoTime});
export const lessonWorkbenchRefSchema=z.object({id:z.string(),lessonId:z.string(),implementationId:z.string(),templateId:z.string(),classId:z.string(),subjectId:z.string(),topicId:z.string(),isActive:z.boolean(),createdAt:isoTime,updatedAt:isoTime});
export type Lesson=z.infer<typeof lessonSchema>;export type LessonPlanning=z.infer<typeof lessonPlanningSchema>;export type LessonPhase=z.infer<typeof lessonPhaseSchema>;export type LessonReflection=z.infer<typeof lessonReflectionSchema>;export type LessonWorkbenchRef=z.infer<typeof lessonWorkbenchRefSchema>;
export const LESSON_STATUS_LABELS:Record<LessonStatus,string>={draft:"Entwurf",planning:"In Planung",ready:"Einsatzbereit",completed:"Abgeschlossen",cancelled:"Abgesagt",needs_revision:"Überarbeiten"};export const LESSON_TRANSITIONS:Record<LessonStatus,LessonStatus[]>={draft:["planning","cancelled"],planning:["ready","needs_revision","cancelled"],ready:["completed","needs_revision","cancelled"],completed:["needs_revision"],cancelled:[],needs_revision:["planning"]};
export function phaseMinutes(phases:LessonPhase[]){return phases.reduce((sum,p)=>sum+p.durationMinutes,0)}export function qualityHints(planning:LessonPlanning,phases:LessonPhase[],duration:number){const hints:string[]=[];if(!planning.lessonGoal)hints.push("Lernziel noch offen.");const sum=phaseMinutes(phases);if(sum!==duration)hints.push(`Die Phasen ergeben ${sum} Minuten, geplant sind ${duration} Minuten.`);if(!phases.some(p=>p.phaseType==="consolidation"))hints.push("Keine erkennbare Sicherung vorhanden.");if(planning.materialNeeds&&!planning.preparation)hints.push("Materialbedarf ist eingetragen, die Vorbereitung ist noch offen.");if(!planning.differentiation)hints.push("Differenzierung ist noch nicht beschrieben.");return hints}
