import type { DomainDatabase } from "./database"; import { domainDb,seedDomain,validate,validators } from "./database";
import { clean,optional,DomainError,type GradeLevel,type TeachingClass,type Topic } from "./model";
const stamp=()=>new Date().toISOString(); const id=()=>crypto.randomUUID(); const same=(a:string,b:string)=>clean(a).toLocaleLowerCase("de-DE")===clean(b).toLocaleLowerCase("de-DE"); const readiness=new WeakMap<DomainDatabase,Promise<void>>();
export class DomainService { constructor(public db:DomainDatabase=domainDb){}
 async ready(){let current=readiness.get(this.db);if(!current){current=seedDomain(this.db).finally(()=>readiness.delete(this.db));readiness.set(this.db,current)}await current;}
 async snapshot(){await this.ready(); const [years,classes,subjects,classSubjects,topics]=await Promise.all([this.db.schoolYears.toArray(),this.db.classes.toArray(),this.db.subjects.toArray(),this.db.classSubjects.toArray(),this.db.topics.toArray()]);return{years:years.map(v=>validate(validators.schoolYear,v)),classes:classes.map(v=>validate(validators.teachingClass,v)),subjects:subjects.map(v=>validate(validators.subject,v)),classSubjects:classSubjects.map(v=>validate(validators.classSubject,v)),topics:topics.map(v=>validate(validators.topic,v))};}
 async createSchoolYear(input:{label:string;startsOn:string;endsOn:string}){if(input.startsOn>=input.endsOn)throw new DomainError("SCHOOL_YEAR_INVALID_RANGE","Das Enddatum muss nach dem Startdatum liegen.");const t=stamp(),value={id:id(),label:clean(input.label),startsOn:input.startsOn,endsOn:input.endsOn,isActive:false,createdAt:t,updatedAt:t};await this.db.schoolYears.add(value);return value;}
 async activateSchoolYear(yearId:string){await this.db.transaction("rw",this.db.schoolYears,async()=>{const y=await this.db.schoolYears.get(yearId);if(!y)throw new DomainError("SCHOOL_YEAR_NOT_FOUND","Schuljahr nicht gefunden.");const t=stamp();await this.db.schoolYears.toCollection().modify({isActive:false,updatedAt:t});await this.db.schoolYears.update(yearId,{isActive:true,archivedAt:undefined,updatedAt:t});});}
 async archiveSchoolYear(yearId:string){const y=await this.db.schoolYears.get(yearId);if(!y)throw new DomainError("SCHOOL_YEAR_NOT_FOUND","Schuljahr nicht gefunden.");if(y.isActive)throw new DomainError("SCHOOL_YEAR_INVALID_RANGE","Das aktive Schuljahr kann nicht archiviert werden.");await this.db.schoolYears.update(yearId,{archivedAt:stamp(),updatedAt:stamp()});}
 async createClass(input:{schoolYearId:string;label:string;gradeLevel:GradeLevel;description?:string;subjectIds:string[]}){return this.db.transaction("rw",this.db.schoolYears,this.db.classes,this.db.subjects,this.db.classSubjects,async()=>{if(!await this.db.schoolYears.get(input.schoolYearId))throw new DomainError("SCHOOL_YEAR_NOT_FOUND","Schuljahr nicht gefunden.");const existing=await this.db.classes.where("schoolYearId").equals(input.schoolYearId).toArray();if(existing.some(c=>!c.archivedAt&&same(c.label,input.label)))throw new DomainError("CLASS_DUPLICATE_LABEL","Diese Klasse gibt es in dem Schuljahr bereits.");if(!input.subjectIds.length)throw new DomainError("SUBJECT_NOT_FOUND","Wähle mindestens ein Fach.");const found=await this.db.subjects.bulkGet(input.subjectIds);if(found.some(v=>!v))throw new DomainError("SUBJECT_NOT_FOUND","Fach nicht gefunden.");const t=stamp(),classId=id();const value:TeachingClass={id:classId,schoolYearId:input.schoolYearId,label:clean(input.label),gradeLevel:input.gradeLevel,description:optional(input.description),isActive:true,createdAt:t,updatedAt:t};await this.db.classes.add(value);await this.db.classSubjects.bulkAdd(input.subjectIds.map((subjectId,sortOrder)=>({id:id(),classId,subjectId,isActive:true,sortOrder,createdAt:t,updatedAt:t})));return value;});}
 async updateClass(classId:string,input:{label:string;gradeLevel:GradeLevel;description?:string|undefined}){const current=await this.db.classes.get(classId);if(!current)throw new DomainError("CLASS_NOT_FOUND","Klasse nicht gefunden.");if(current.archivedAt)throw new DomainError("CLASS_ARCHIVED","Die Klasse ist archiviert.");const peers=await this.db.classes.where("schoolYearId").equals(current.schoolYearId).toArray();if(peers.some(c=>c.id!==classId&&!c.archivedAt&&same(c.label,input.label)))throw new DomainError("CLASS_DUPLICATE_LABEL","Diese Klasse gibt es bereits.");await this.db.classes.update(classId,{label:clean(input.label),gradeLevel:input.gradeLevel,description:optional(input.description),updatedAt:stamp()});}
 async archiveClass(classId:string){const c=await this.db.classes.get(classId);if(!c)throw new DomainError("CLASS_NOT_FOUND","Klasse nicht gefunden.");await this.db.classes.update(classId,{isActive:false,archivedAt:stamp(),updatedAt:stamp()});}
 async setSubjectActive(classId:string,subjectId:string,active:boolean){const c=await this.db.classes.get(classId);if(!c)throw new DomainError("CLASS_NOT_FOUND","Klasse nicht gefunden.");if(!await this.db.subjects.get(subjectId))throw new DomainError("SUBJECT_NOT_FOUND","Fach nicht gefunden.");const row=await this.db.classSubjects.where("[classId+subjectId]").equals([classId,subjectId]).first();if(row)await this.db.classSubjects.update(row.id,{isActive:active,updatedAt:stamp()});else if(active)await this.db.classSubjects.add({id:id(),classId,subjectId,isActive:true,sortOrder:await this.db.classSubjects.where("classId").equals(classId).count(),createdAt:stamp(),updatedAt:stamp()});}
 async reorderSubjects(classId:string,subjectId:string,direction:-1|1){const rows=(await this.db.classSubjects.where("classId").equals(classId).toArray()).filter(r=>r.isActive).sort((a,b)=>a.sortOrder-b.sortOrder);await reorder(this.db.classSubjects,rows,subjectId,direction);}
 async createTopic(input:{classId:string;subjectId:string;title:string;description?:string}){const relation=await this.db.classSubjects.where("[classId+subjectId]").equals([input.classId,input.subjectId]).first();if(!relation?.isActive)throw new DomainError("CLASS_SUBJECT_NOT_ACTIVE","Das Fach ist für diese Klasse nicht aktiv.");await this.ensureTopicUnique(input.classId,input.subjectId,input.title);const t=stamp(),value:Topic={id:id(),classId:input.classId,subjectId:input.subjectId,title:clean(input.title),description:optional(input.description),sortOrder:await this.db.topics.where("[classId+subjectId]").equals([input.classId,input.subjectId]).count(),status:"active",createdAt:t,updatedAt:t};await this.db.topics.add(value);return value;}
 async renameTopic(topicId:string,title:string,description?:string){const topic=await this.db.topics.get(topicId);if(!topic)throw new DomainError("TOPIC_NOT_FOUND","Thema nicht gefunden.");if(topic.status==="archived")throw new DomainError("TOPIC_ARCHIVED","Das Thema ist archiviert.");await this.ensureTopicUnique(topic.classId,topic.subjectId,title,topic.id);await this.db.topics.update(topicId,{title:clean(title),description:optional(description),updatedAt:stamp()});}
 async archiveTopic(topicId:string){const topic=await this.db.topics.get(topicId);if(!topic)throw new DomainError("TOPIC_NOT_FOUND","Thema nicht gefunden.");await this.db.topics.update(topicId,{status:"archived",archivedAt:stamp(),updatedAt:stamp()});}
 async restoreTopic(topicId:string){const topic=await this.db.topics.get(topicId);if(!topic)throw new DomainError("TOPIC_NOT_FOUND","Thema nicht gefunden.");await this.ensureTopicUnique(topic.classId,topic.subjectId,topic.title,topic.id);const{archivedAt:_,...rest}=topic;await this.db.topics.put({...rest,status:"active",updatedAt:stamp()});}
 async reorderTopics(classId:string,subjectId:string,topicId:string,direction:-1|1){const rows=(await this.db.topics.where("[classId+subjectId]").equals([classId,subjectId]).toArray()).filter(r=>r.status==="active").sort((a,b)=>a.sortOrder-b.sortOrder);await reorder(this.db.topics,rows,topicId,direction);}
 private async ensureTopicUnique(classId:string,subjectId:string,title:string,except?:string){const rows=await this.db.topics.where("[classId+subjectId]").equals([classId,subjectId]).toArray();if(rows.some(t=>t.id!==except&&same(t.title,title)))throw new DomainError("TOPIC_DUPLICATE_TITLE","Dieses Thema gibt es in dem Fach bereits.");}
}
async function reorder(table:any,rows:{id:string;sortOrder:number}[],target:string,direction:-1|1){const i=rows.findIndex(r=>r.id===target);if(i<0)return;const current=rows[i],other=rows[i+direction];if(!current||!other)return;await table.bulkPut([{...current,sortOrder:other.sortOrder,updatedAt:stamp()},{...other,sortOrder:current.sortOrder,updatedAt:stamp()}]);}
export const domainService=new DomainService();
