import Fastify from "fastify";import cookie from "@fastify/cookie";import cors from "@fastify/cors";import helmet from "@fastify/helmet";import rateLimit from "@fastify/rate-limit";import {randomUUID}from"node:crypto";import {readConfig,type ApiConfig}from"./config.js";import{Store,type Session}from"./store.js";import{localImportSchema,buddyRequestSchema,resourceInputSchema}from"../../../packages/contracts/api.js";import{MockBuddyProvider}from"./buddy/provider.js";
declare module "fastify"{interface FastifyRequest{session?:Session}}
const messages:Record<string,string>={AUTH_REQUIRED:"Bitte melde dich erneut an.",SESSION_EXPIRED:"Die Sitzung ist abgelaufen.",CSRF_INVALID:"Die Sicherheitsprüfung ist fehlgeschlagen.",ORIGIN_DENIED:"Diese Herkunft ist nicht freigegeben.",RESOURCE_NOT_FOUND:"Der Inhalt wurde nicht gefunden.",RESOURCE_VERSION_CONFLICT:"Der Inhalt wurde inzwischen geändert.",IMPORT_CONFLICT:"Die Importvorschau ist nicht mehr aktuell.",IMPORT_ALREADY_APPLIED:"Dieser Import wurde bereits durchgeführt.",BUDDY_RATE_LIMITED:"Bitte warte kurz vor der nächsten Buddy-Anfrage.",BUDDY_BUDGET_EXCEEDED:"Das heutige Buddy-Limit ist erreicht.",INTERNAL_ERROR:"Die Anfrage konnte nicht verarbeitet werden."};
export async function buildApp(opts:{config?:ApiConfig;store?:Store}={}){const config=opts.config??readConfig(),store=opts.store??new Store(),app=Fastify({logger:false,bodyLimit:256_000,requestTimeout:15_000,genReqId:()=>randomUUID()});await app.register(cookie);await app.register(cors,{origin:config.FRONTEND_ORIGIN,credentials:true});await app.register(helmet,{global:true,contentSecurityPolicy:{directives:{defaultSrc:["'self'"]}}});await app.register(rateLimit,{global:true,max:200,timeWindow:"1 minute"});
 const fail=(reply:any,request:any,code:string,status=400)=>reply.code(status).send({error:{code,message:messages[code]??messages.INTERNAL_ERROR,requestId:request.id}});
 app.addHook("onRequest",async(req,reply)=>{reply.header("Permissions-Policy","camera=(), microphone=(), geolocation=()");if(["POST","PUT","PATCH","DELETE"].includes(req.method)&&!req.url.startsWith("/api/v1/auth/mock-login")){if(req.headers.origin!==config.FRONTEND_ORIGIN)return fail(reply,req,"ORIGIN_DENIED",403)}});
 app.addHook("preHandler",async(req,reply)=>{if(req.url.startsWith("/api/v1/health")||req.url.startsWith("/api/v1/readiness")||req.url.startsWith("/api/v1/auth/mock-login"))return;const sid=req.cookies.lk_session,s=sid?store.sessions.get(sid):undefined;if(!s)return fail(reply,req,"AUTH_REQUIRED",401);if(s.expiresAt<Date.now()){store.sessions.delete(s.id);return fail(reply,req,"SESSION_EXPIRED",401)}req.session=s;if(["POST","PUT","PATCH","DELETE"].includes(req.method)&&req.headers["x-csrf-token"]!==s.csrf)return fail(reply,req,"CSRF_INVALID",403)});
 app.get("/api/v1/health",async()=>({status:"ok"}));app.get("/api/v1/readiness",async()=>({status:"ready",database:"configured",identity:config.IDENTITY_MODE,openai:config.OPENAI_API_KEY?"configured":"prepared"}));
 app.post("/api/v1/auth/mock-login",{config:{rateLimit:{max:10,timeWindow:"1 minute"}}},async(req,reply)=>{if(config.IDENTITY_MODE!=="mock")return fail(reply,req,"AUTH_REQUIRED",404);const id=(req.body as any)?.userId;try{const s=store.session(id);reply.setCookie("lk_session",s.id,{httpOnly:true,sameSite:"strict",secure:config.NODE_ENV==="production",path:"/",maxAge:3600});store.audit(s,"auth.login","success");return{user:store.users.get(id),workspace:store.workspaces.get(s.workspaceId),csrfToken:s.csrf}}catch{return fail(reply,req,"AUTH_REQUIRED",401)}});
 app.get("/api/v1/session",async(req)=>({user:store.users.get(req.session!.userId),workspace:store.workspaces.get(req.session!.workspaceId),csrfToken:req.session!.csrf}));app.post("/api/v1/auth/logout",async(req,reply)=>{store.audit(req.session!,"auth.logout","success");store.sessions.delete(req.session!.id);reply.clearCookie("lk_session",{path:"/"});return{ok:true}});
 app.get("/api/v1/bootstrap",async(req)=>({user:store.users.get(req.session!.userId),workspace:store.workspaces.get(req.session!.workspaceId),featureFlags:{serverBuddy:true,localImport:true},sync:{automatic:false}}));
 app.get("/api/v1/workbench",async(req)=>({items:[...store.resources.values()].filter(r=>r.workspaceId===req.session!.workspaceId&&!r.archivedAt)}));app.get("/api/v1/classes",async(req)=>({items:[...store.resources.values()].filter(r=>r.workspaceId===req.session!.workspaceId&&r.kind==="class"&&!r.archivedAt)}));
 for(const [plural,kind]of[["series","series"],["lessons","lesson"],["materials","material"]]as const)app.get(`/api/v1/${plural}/:id`,async(req,reply)=>{const r=store.own(req.session!.workspaceId,(req.params as any).id);if(!r||r.kind!==kind){store.audit(req.session!,"resource.read","denied");return fail(reply,req,"RESOURCE_NOT_FOUND",404)}return r});
 app.post("/api/v1/resources",async(req,reply)=>{const x=resourceInputSchema.safeParse(req.body);if(!x.success)return fail(reply,req,"INTERNAL_ERROR",400);if(x.data.parentId&&!store.own(req.session!.workspaceId,x.data.parentId))return fail(reply,req,"RESOURCE_NOT_FOUND",404);const r={id:randomUUID(),workspaceId:req.session!.workspaceId,kind:x.data.kind,title:x.data.title,version:1,...(x.data.parentId?{parentId:x.data.parentId}:{})};store.resources.set(r.id,r);store.audit(req.session!,"resource.create","success",r.id);return reply.code(201).send(r)});
 app.patch("/api/v1/resources/:id",async(req,reply)=>{const r=store.own(req.session!.workspaceId,(req.params as any).id),x=resourceInputSchema.partial().safeParse(req.body);if(!r||!x.success)return fail(reply,req,"RESOURCE_NOT_FOUND",404);if(x.data.version!==r.version)return fail(reply,req,"RESOURCE_VERSION_CONFLICT",409);if(x.data.title)r.title=x.data.title;r.version++;store.audit(req.session!,"resource.update","success",r.id);return r});app.delete("/api/v1/resources/:id",async(req,reply)=>{const r=store.own(req.session!.workspaceId,(req.params as any).id);if(!r)return fail(reply,req,"RESOURCE_NOT_FOUND",404);r.archivedAt=new Date().toISOString();store.audit(req.session!,"resource.archive","success",r.id);return{ok:true}});
 app.post("/api/v1/import/local-preview",async(req,reply)=>{const x=localImportSchema.safeParse(req.body);if(!x.success)return fail(reply,req,"IMPORT_CONFLICT",400);const out=store.preview(req.session!,x.data);store.audit(req.session!,"import.preview","success");return out});app.post("/api/v1/import/local-commit",async(req,reply)=>{try{return store.commit(req.session!,(req.body as any).previewId,(req.body as any).hash)}catch(e){return fail(reply,req,(e as Error).message,409)}});
 const buddy=new MockBuddyProvider();app.post("/api/v1/buddy/requests",{config:{rateLimit:{max:10,timeWindow:"1 minute"}}},async(req,reply)=>{const x=buddyRequestSchema.safeParse(req.body);if(!x.success)return fail(reply,req,"INTERNAL_ERROR");const target=store.own(req.session!.workspaceId,x.data.targetId);if(!target)return fail(reply,req,"RESOURCE_NOT_FOUND",404);const used=store.buddyUsage.get(req.session!.workspaceId)??0;if(used>=50)return fail(reply,req,"BUDDY_BUDGET_EXCEEDED",429);store.buddyUsage.set(req.session!.workspaceId,used+1);const suggestion={id:randomUUID(),targetId:target.id,baseVersion:target.version,...await buddy.generate(target.title)};store.audit(req.session!,"buddy.request","success",target.id);return suggestion});
 app.get("/api/v1/audit",async(req)=>({items:store.audits.filter(a=>a.workspaceId===req.session!.workspaceId)}));return Object.assign(app,{store})}

