import { randomUUID, createHash } from "node:crypto";
import type { LocalImport, ResourceKind } from "../../../packages/contracts/api.js";
export type User={id:string;providerSubject:string;accountType:"personal"|"work_school";displayName:string;disabledAt?:string};
export type Workspace={id:string;ownerUserId:string;name:string;archivedAt?:string};
export type Session={id:string;userId:string;workspaceId:string;csrf:string;expiresAt:number};
export type Resource={id:string;workspaceId:string;kind:ResourceKind;title:string;parentId?:string;version:number;archivedAt?:string};
export type Audit={workspaceId:string;actorUserId:string;action:string;outcome:"success"|"failure"|"denied";targetId?:string};
export class Store{
 users=new Map<string,User>(); workspaces=new Map<string,Workspace>(); sessions=new Map<string,Session>(); resources=new Map<string,Resource>(); audits:Audit[]=[]; previews=new Map<string,{workspaceId:string;hash:string;payload:LocalImport}>(); imports=new Set<string>(); buddyUsage=new Map<string,number>();
 constructor(){this.seed()}
 seed(){const seeds:[string,string,string,string,string,string,string][]=[["personal-user-a","workspace-a","Klasse 2a","Nomen","Nomen entdecken","Stunde A","Material A"],["personal-user-b","workspace-b","Klasse 3a","Lesen","Lesen entdecken","Stunde B","Material B"]];for(const [u,w,c,t,s,l,m] of seeds){this.users.set(u,{id:u,providerSubject:u,accountType:"personal",displayName:u==="personal-user-a"?"Ute Test":"Kollegin Test"});this.workspaces.set(w,{id:w,ownerUserId:u,name:`Arbeitsplatz ${u.at(-1)?.toUpperCase()}`});let parent:string|undefined;for(const [kind,title] of [["class",c],["topic",t],["series",s],["lesson",l],["material",m]] as [ResourceKind,string][]){const id=`${kind}-${u.at(-1)}`;this.resources.set(id,{id,workspaceId:w,kind,title,version:1,...(parent?{parentId:parent}:{})});parent=id}}}
 session(userId:string){const old=[...this.sessions.values()].find(x=>x.userId===userId);if(old)this.sessions.delete(old.id);const u=this.users.get(userId);if(!u||u.disabledAt)throw new Error("AUTH_ACCOUNT_DISABLED");const w=[...this.workspaces.values()].find(x=>x.ownerUserId===userId)!;const s={id:randomUUID(),userId,workspaceId:w.id,csrf:randomUUID(),expiresAt:Date.now()+3600_000};this.sessions.set(s.id,s);return s}
 own(workspaceId:string,id:string){const r=this.resources.get(id);return r?.workspaceId===workspaceId&&!r.archivedAt?r:undefined}
 audit(s:Session,action:string,outcome:Audit["outcome"],targetId?:string){this.audits.push({workspaceId:s.workspaceId,actorUserId:s.userId,action,outcome,...(targetId?{targetId}:{})})}
 preview(s:Session,payload:LocalImport){const hash=createHash("sha256").update(JSON.stringify(payload)).digest("hex"),id=randomUUID();this.previews.set(id,{workspaceId:s.workspaceId,hash,payload});return{id,hash,valid:payload.objects.length,invalid:0,duplicates:payload.objects.filter(o=>[...this.resources.values()].some(r=>r.workspaceId===s.workspaceId&&r.kind===o.kind&&r.title===o.title)).length,targetWorkspace:s.workspaceId}}
 commit(s:Session,id:string,hash:string){const p=this.previews.get(id);if(!p||p.workspaceId!==s.workspaceId||p.hash!==hash)throw new Error("IMPORT_CONFLICT");const key=`${s.workspaceId}:${hash}`;if(this.imports.has(key))throw new Error("IMPORT_ALREADY_APPLIED");const map=new Map<string,string>();for(const o of p.payload.objects)map.set(o.localId,randomUUID());for(const o of p.payload.objects)this.resources.set(map.get(o.localId)!,{id:map.get(o.localId)!,workspaceId:s.workspaceId,kind:o.kind,title:o.title,version:1,...(o.parentLocalId&&map.get(o.parentLocalId)?{parentId:map.get(o.parentLocalId)!}:{})});this.imports.add(key);this.audit(s,"import.commit","success");return{imported:p.payload.objects.length,mapping:Object.fromEntries(map)}}
}
