// @vitest-environment jsdom
import { render,screen,within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { beforeEach,describe,expect,it } from "vitest";
import { AppRoutes } from "../../../app/router";
import { WORKBENCH_STORAGE_KEY } from "../workbench-storage";

function renderAt(path="/werkbank"){return render(<MemoryRouter initialEntries={[path]}><AppRoutes/></MemoryRouter>);}
function cardFor(title:string){return screen.getByRole("heading",{name:title}).closest("section") as HTMLElement;}
beforeEach(()=>localStorage.clear());

describe("Werkbank",()=>{
  it("zeigt künstliche Demo-Einträge in passenden Bereichen",()=>{renderAt();expect(screen.getByRole("heading",{name:"Angeheftet"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Aktuelle Arbeiten"})).toBeInTheDocument();expect(screen.getByText("Nomen entdecken")).toBeInTheDocument();expect(screen.getByText("Arbeitsblatt: Nomen mit Artikeln")).toBeInTheDocument();});
  it("navigiert mit Weiterarbeiten und aktualisiert den Zeitpunkt",async()=>{const user=userEvent.setup();renderAt();const card=cardFor("Arbeitsblatt: Nomen mit Artikeln");await user.click(within(card).getByRole("button",{name:"Weiterarbeiten"}));expect((await screen.findAllByRole("heading",{name:"Nomen mit Artikeln erkennen"})).length).toBeGreaterThan(0);const stored=JSON.parse(localStorage.getItem(WORKBENCH_STORAGE_KEY)??"{}");expect(stored.overrides["material-worksheet"].lastEditedAt).toMatch(/^\d{4}-/);expect(screen.getByText(/Drucknahe Arbeitsansicht/)).toBeInTheDocument();});
  it("heftet per Tastatur an und löst die Anheftung",async()=>{const user=userEvent.setup();renderAt();const card=cardFor("Arbeitsblatt: Nomen mit Artikeln");const pin=within(card).getByRole("button",{name:"Anheften"});pin.focus();await user.keyboard("{Enter}");expect(within(cardFor("Arbeitsblatt: Nomen mit Artikeln")).getByText("Angeheftet")).toBeInTheDocument();await user.click(within(cardFor("Arbeitsblatt: Nomen mit Artikeln")).getByRole("button",{name:"Nicht mehr anheften"}));expect(within(cardFor("Arbeitsblatt: Nomen mit Artikeln")).queryByText("Angeheftet")).not.toBeInTheDocument();});
  it("stellt Anheftstatus nach Remount wieder her",async()=>{const user=userEvent.setup();const first=renderAt();await user.click(within(cardFor("Arbeitsblatt: Nomen mit Artikeln")).getByRole("button",{name:"Anheften"}));first.unmount();renderAt();expect(within(cardFor("Arbeitsblatt: Nomen mit Artikeln")).getByText("Angeheftet")).toBeInTheDocument();});
  it("bricht Entfernen ohne Änderung ab",async()=>{const user=userEvent.setup();renderAt();await user.click(within(cardFor("Nomen entdecken")).getByRole("button",{name:"Von Werkbank nehmen"}));const dialog=screen.getByRole("dialog",{name:"Von der Werkbank nehmen?"});expect(dialog).toHaveTextContent("bleibt gespeichert");await user.click(within(dialog).getByRole("button",{name:"Abbrechen"}));expect(screen.getByText("Nomen entdecken")).toBeInTheDocument();});
  it("entfernt nur den Verweis, bietet Rückgängig und bleibt nach Remount entfernt",async()=>{const user=userEvent.setup();const first=renderAt();await user.click(within(cardFor("Nomen entdecken")).getByRole("button",{name:"Von Werkbank nehmen"}));await user.click(within(screen.getByRole("dialog",{name:"Von der Werkbank nehmen?"})).getByRole("button",{name:"Von Werkbank nehmen"}));expect(screen.queryByText("Nomen entdecken")).not.toBeInTheDocument();expect(screen.getByText(/wurde von der Werkbank genommen/).closest('[role="status"]')).toBeInTheDocument();first.unmount();renderAt();expect(screen.queryByText("Nomen entdecken")).not.toBeInTheDocument();});
  it("stellt einen entfernten Eintrag mit Rückgängig wieder her",async()=>{const user=userEvent.setup();renderAt();await user.click(within(cardFor("Nomen entdecken")).getByRole("button",{name:"Von Werkbank nehmen"}));await user.click(within(screen.getByRole("dialog",{name:"Von der Werkbank nehmen?"})).getByRole("button",{name:"Von Werkbank nehmen"}));const undoNotice=screen.getByText(/wurde von der Werkbank genommen/).closest('[role="status"]') as HTMLElement;await user.click(within(undoNotice).getByRole("button",{name:"Rückgängig"}));expect(screen.getByText("Nomen entdecken")).toBeInTheDocument();});
  it("zeigt die leere Werkbank mit höchstens drei Aktionen",()=>{renderAt("/werkbank?state=empty");expect(screen.getByRole("heading",{name:"Deine Werkbank ist frei."})).toBeInTheDocument();const state=screen.getByRole("heading",{name:"Deine Werkbank ist frei."}).closest("div") as HTMLElement;expect(within(state).getAllByRole("button")).toHaveLength(3);});
  it("filtert lokal ausschließlich Materialien",async()=>{const user=userEvent.setup();renderAt();await user.click(screen.getByRole("radio",{name:"Materialien"}));expect(screen.getByText("Arbeitsblatt: Nomen mit Artikeln")).toBeInTheDocument();expect(screen.queryByText("Nomen mit Artikeln erkennen")).not.toBeInTheDocument();});
  it("macht Status als Text erkennbar",()=>{renderAt();expect(within(cardFor("Nomen mit Artikeln erkennen")).getByText("Einsatzbereit")).toBeInTheDocument();});
  it("speichert den Tagesfokus lokal und zeigt ihn nach erneutem Öffnen",async()=>{const user=userEvent.setup();const first=renderAt();await user.click(screen.getByRole("button",{name:"Bearbeiten"}));const dialog=screen.getByRole("dialog",{name:"Tagesfokus bearbeiten"});const field=within(dialog).getByLabelText("Was ist heute wichtig?");await user.clear(field);await user.type(field,"Deutschplanung abschließen");await user.click(within(dialog).getByRole("button",{name:"Fokus speichern"}));expect(screen.getByText("Deutschplanung abschließen")).toBeInTheDocument();first.unmount();renderAt();expect(screen.getByText("Deutschplanung abschließen")).toBeInTheDocument();});
  it("bietet echte Ziele statt Später-verfügbar-Dialogen",()=>{renderAt();expect(screen.getByRole("link",{name:"Neue Unterrichtsreihe"})).toHaveAttribute("href","/reihen/neu");expect(screen.getByRole("link",{name:"Material erstellen"})).toHaveAttribute("href","/materialien/neu");expect(screen.getByRole("link",{name:"Jetzt sichern"})).toHaveAttribute("href","/einstellungen/sicherung");expect(screen.queryByText(/späteren Paket/)).not.toBeInTheDocument();});
});