// @vitest-environment jsdom
import {beforeEach,describe,expect,it} from "vitest";import {render,screen,within} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {MemoryRouter} from "react-router-dom";import {AppRoutes} from "../../app/router";import {domainDb} from "../../domain";
beforeEach(async()=>{localStorage.clear();await domainDb.delete();await domainDb.open()});const at=(p:string)=>render(<MemoryRouter initialEntries={[p]}><AppRoutes/></MemoryRouter>);
describe("Kalenderoberflächen",()=>{
it("zeigt Demo-Wochenstundenplan",async()=>{at("/stundenplan");expect(await screen.findByRole("heading",{name:"Woche vom 24. bis 28. August 2026"})).toBeInTheDocument();expect(screen.getByText("Nomen kennenlernen")).toBeInTheDocument()});
it("wechselt Tagesansicht und speichert Auswahl",async()=>{const u=userEvent.setup();at("/stundenplan");await screen.findByRole("heading",{name:"Stundenplan"});await u.click(screen.getByLabelText("Tag"));expect(await screen.findByRole("heading",{name:"Tagesansicht 24.08.2026"})).toBeInTheDocument();expect(localStorage.getItem("lehrerkompass.calendar.view")).toBe("Tag")});
it("navigiert zum nächsten Schultag",async()=>{const u=userEvent.setup();localStorage.setItem("lehrerkompass.calendar.view","Tag");at("/stundenplan");await u.click(await screen.findByRole("button",{name:"Nächster Schultag"}));expect(screen.getByDisplayValue("2026-08-25")).toBeInTheDocument()});
it("öffnet Einplanen aus der Unterrichtsstunde",async()=>{at("/stundenplan?lessonId=lesson-nomen-1");expect(await screen.findByRole("dialog",{name:"Unterrichtsstunde einplanen"})).toBeInTheDocument();expect(screen.getByLabelText("Unterrichtsstunde")).toHaveValue("lesson-nomen-1")});
it("zeigt Konflikt verständlich",async()=>{const u=userEvent.setup();at("/stundenplan?lessonId=lesson-nomen-1");await screen.findByRole("dialog");await u.selectOptions(screen.getByLabelText("Unterrichtsblock"),"period-1");await u.click(screen.getByRole("button",{name:"Termin verbindlich anlegen"}));expect(await screen.findByRole("alert")).toHaveTextContent("bereits eingeplant")});
it("öffnet Termin",async()=>{at("/kalender/termine/calendar-event-nomen");expect(await screen.findByRole("heading",{name:"Nomen kennenlernen"})).toBeInTheDocument();expect(screen.getByText("Unterrichtsstunde öffnen")).toBeInTheDocument()});
it("öffnet Verschiebedialog",async()=>{const u=userEvent.setup();at("/kalender/termine/calendar-event-nomen");await u.click(await screen.findByRole("button",{name:"Verschieben"}));expect(screen.getByRole("dialog",{name:"Termin verschieben"})).toBeInTheDocument()});
it("öffnet Ausfalldialog mit Trennungshinweis",async()=>{const u=userEvent.setup();at("/kalender/termine/calendar-event-nomen");await u.click(await screen.findByRole("button",{name:"Termin fällt aus"}));expect(screen.getByText(/Unterrichtsstunde und ihre Planung bleiben erhalten/)).toBeInTheDocument()});
it("fordert für Stundenabschluss eine eigene Bestätigung",async()=>{const u=userEvent.setup();at("/kalender/termine/calendar-event-nomen");await u.click(await screen.findByRole("button",{name:"Als durchgeführt markieren"}));expect(screen.getByRole("checkbox",{name:/Zugehörige Unterrichtsstunde/})).not.toBeChecked()});
it("zeigt ungeplante Stunden nach Anlage",async()=>{at("/stundenplan");expect(await screen.findByRole("heading",{name:"Noch nicht eingeplant"})).toBeInTheDocument()});
it("öffnet Sondertermin-Dialog",async()=>{const u=userEvent.setup();at("/stundenplan");await u.click(await screen.findByRole("button",{name:"Schulischen Termin anlegen"}));expect(screen.getByRole("dialog",{name:"Schulischen Termin anlegen"})).toBeInTheDocument()});
it("zeigt Tagesübersicht",async()=>{at("/tagesuebersicht/2026-08-24");expect(await screen.findByRole("heading",{name:"Tagesübersicht"})).toBeInTheDocument();expect(screen.getByText("Nomen kennenlernen")).toBeInTheDocument()});
it("zeigt datenschutzreduzierte Vertretungsansicht",async()=>{at("/vertretungsuebersicht/2026-08-24");expect(await screen.findByText("Für die Weitergabe reduzierte Ansicht.")).toBeInTheDocument();expect(screen.queryByText(/Interne Beobachtung|Private Notiz:/)).not.toBeInTheDocument()});
it("zeigt Einstellungen und Demo-Blöcke",async()=>{at("/stundenplan/einstellungen");expect(await screen.findByRole("heading",{name:"Unterrichtsblöcke"})).toBeInTheDocument();expect(screen.getByText("08:00–08:45 · Aktiv")).toBeInTheDocument()});
it("Werkbank verweist auf echte Tagesübersicht",async()=>{at("/werkbank");const card=(await screen.findByText("Tagesübersicht Montag")).closest("section")!;expect(within(card).getByRole("button",{name:"Weiterarbeiten"})).toBeInTheDocument()});
it("zeigt ungültigen Termin ruhig",async()=>{at("/kalender/termine/unbekannt");expect(await screen.findByRole("heading",{name:"Termin nicht gefunden"})).toBeInTheDocument()});
});
