import type { WorkbenchItem } from "./workbench-model";

export const DEMO_WORKBENCH_ITEMS: WorkbenchItem[] = [
  { id:"series-nouns",type:"series",title:"Nomen entdecken",classId:"class-2a",subjectId:"subject-deutsch",topicId:"topic-nomen",templateId:"template-nomen",implementationId:"implementation-nomen",classLabel:"Klasse 2a",subjectLabel:"Deutsch",topicLabel:"Nomen",status:"planning",nextStep:"Grundplanung bearbeiten",progressText:"6 Gliederungspunkte",lastEditedAt:"2026-07-15T08:30:00.000Z",pinned:true,removedFromWorkbench:false,targetRoute:"/reihen/implementation-nomen" },
  { id:"lesson-articles",type:"lesson",title:"Nomen mit Artikeln erkennen",classId:"class-2a",subjectId:"subject-deutsch",topicId:"topic-nomen",templateId:"template-nomen",implementationId:"implementation-nomen",lessonId:"lesson-nomen-1",classLabel:"Klasse 2a",subjectLabel:"Deutsch",topicLabel:"Nomen",subtitle:"Stunde 1",status:"ready",nextStep:"Lernziel formulieren",lastEditedAt:"2026-07-15T07:40:00.000Z",pinned:false,removedFromWorkbench:false,targetRoute:"/stunden/lesson-nomen-1" },
  { id:"material-worksheet",type:"material",title:"Arbeitsblatt: Nomen mit Artikeln",classId:"class-2a",subjectId:"subject-deutsch",topicId:"topic-nomen",lessonId:"lesson-nomen-1",materialId:"material-nomen-standard",familyId:"family-nomen",variantId:"variant-nomen-standard",classLabel:"Klasse 2",subjectLabel:"Deutsch",status:"draft",nextStep:"Lösung prüfen",lastEditedAt:"2026-07-14T15:20:00.000Z",pinned:false,removedFromWorkbench:false,targetRoute:"/materialien/material-nomen-standard" },
  { id:"support-reading",type:"support-series",title:"Lesetraining in der Kleingruppe",subtitle:"Förderunterricht",status:"planning",nextStep:"Einheit 2 vorbereiten",lastEditedAt:"2026-07-13T12:00:00.000Z",pinned:false,removedFromWorkbench:false,targetRoute:"/prototyp/foerderreihe/lesetraining" },
  { id:"day-thursday",type:"day-overview",title:"Tagesübersicht Montag",subtitle:"Unterrichtstag",dayDate:"2026-08-24",status:"draft",nextStep:"Hinweise für Vertretung prüfen",nextDate:"2026-08-24",lastEditedAt:"2026-07-12T09:10:00.000Z",pinned:false,removedFromWorkbench:false,targetRoute:"/tagesuebersicht/2026-08-24" },
  { id:"series-complete",type:"series",title:"Wortarten wiederholen",classLabel:"Klasse 2",subjectLabel:"Deutsch",status:"completed",nextStep:"Bei Bedarf wieder öffnen",lastEditedAt:"2026-07-10T10:00:00.000Z",pinned:false,removedFromWorkbench:false,targetRoute:"/prototyp/reihe/wortarten" }
];
